# Generated by Django 5.0.3 on 2024-03-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Sub',
        ),
    ]
