# Generated by Django 5.0.3 on 2024-03-27 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_attendance_attendance_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.student'),
        ),
        migrations.AlterField(
            model_name='attendance_report',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.student'),
        ),
    ]
